feat: append to current property value if it exists
szenius/notion-update-page pull request #17
Opened 2022-02-03 16:36 UTC by ilhaoni

[Notion link](https://www.notion.so/szenius/Allow-append-to-field-90d9312ba0cd44619e5b2f2391e2fab8)

This PR appends the new property value to the current property value if it exists. Have also updated README :D 

### Test results from running on my personal Notion and GitHub actions

**First version tag created**
![first-version-tag](https://user-images.githubusercontent.com/5070244/152386230-ee8e5aa1-5d28-4a7a-9fcc-9a0fbc1e16a4.png)

**Second version tag is appended after the first version tag**
![second-version-tag](https://user-images.githubusercontent.com/5070244/152386244-57ca6f38-0e93-436d-b030-7fc97a377b51.png)

2022-02-04 16:15 UTC, szenius requested changes

2022-02-04 16:15 UTC, szenius commented on dist/index.js
>  /***/ ((module) => {
No need to update this file, it will be automatically updated on push

2022-02-04 16:15 UTC, szenius commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
This is a constant so would prefer the variable to be of `UPPER_SNAKE_CASE`. The key names should be `UPPER_SNAKE_CASE` as well.

But also this looks like it could be an enum, although I am not sure if the operations involving this object will become harder to do. Maybe can explore?

2022-02-04 16:15 UTC, szenius commented on index.js
> +      });
Think this is unnecessary duplication from lines 30 to 37. Could get the value to be updated and do the conditional at this step before writing this block.

Array.join might be useful for doing the conditional?

2022-02-04 16:15 UTC, szenius commented on index.js
> +          multi_select: existingPropertyValues,
Naming of `existingPropertyValues` a bit confusing, maybe just `selectValues` is ok

2022-02-04 16:15 UTC, szenius commented on index.js
> +    existingPropertyValues.push({"name": value})
Sorry never set up linter properly 😆  But do still add the `;` 🙏🏼

2022-02-04 16:15 UTC, szenius commented on index.js
> +      notionPropertyType: process.env.NOTION_PROPERTY_TYPE,
Can do the defaulting to rich text here since this is where config is parsed. Easier to figure out the default value from here as compared to somewhere in the middle of the code

2022-02-04 16:15 UTC, szenius commented on index.js
> +    notionPropertyType: core.getInput("notion-property-type"),
Same comment about doing the defaulting here

2022-02-04 16:15 UTC, szenius commented on index.js
> +  if (!(notionPropertyType in supportedPropertyTypes)) {
Not a big issue here but [it's good practice to use `hasOwnProperty` instead of `in`](https://masteringjs.io/tutorials/fundamentals/hasownproperty)

2022-02-10 11:37 UTC, ilhaoni commented on .github/workflows/on_master.yml
> +          git config --local user.name "ilhaoni"
Yeah unintentional, sorry the branch was in a messy state when I raised it for PR review ><

Have rebased!

2022-02-10 11:38 UTC, ilhaoni commented on .github/workflows/on_master.yml
> +          gh-username: "ilhaoni"
Yeah unintentional, sorry the branch was in a messy state when I raised it for PR review ><

Have rebased!

2022-02-10 11:39 UTC, ilhaoni commented on README.md
> +- Current appending logic assumes that no formatting is done in the property, i.e. all plain text only
Yeah this was the old README LOL, before we catered for the multi_select, sorry the branch was in a messy state when I raised it for PR review ><

Have rebased and this is now removed!

2022-02-10 11:40 UTC, ilhaoni commented on README.md
> +
Thanks! agree that this is clearer too! ^^

2022-02-10 11:41 UTC, ilhaoni commented on dist/index.js
>  /***/ ((module) => {
Yeah unintentional, I know it'll be updated on push, sorry the branch was in a messy state when I raised it for PR review ><

Have rebased, this is no longer part of this PR!

2022-02-10 11:51 UTC, ilhaoni commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
OK~ will make the changes so that they're all upper snake cased haha.

I was searching through a few links about javascript enums~ ([here](https://www.sohamkamani.com/javascript/enums/) and [here](https://masteringjs.io/tutorials/fundamentals/enum)), but there isn't a method that I fancy. What are your thoughts? \\^^/

2022-02-10 11:56 UTC, ilhaoni commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
Found [this](https://2ality.com/2020/01/enum-pattern.html) too~

2022-02-13 09:20 UTC, ilhaoni commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
I've made everything uppercased here for the time being: https://github.com/szenius/notion-update-page/pull/17/commits/4f27fc5f16fe40750184ca20f83107cfe19956c9 

I'm thinking maybe the enums can be tried in another PR?

2022-02-13 09:21 UTC, ilhaoni commented on index.js
> +      });
That's a good point~ have refactored it to simplify it here~ https://github.com/szenius/notion-update-page/pull/17/commits/d271776637a33df4024de9a7fa6eda20d063f789

2022-02-13 09:21 UTC, ilhaoni commented on index.js
> +          multi_select: existingPropertyValues,
Have refactored it here! https://github.com/szenius/notion-update-page/pull/17/commits/593c94b3972c24c006dd5c53a845c71a31bc73af

2022-02-13 09:21 UTC, ilhaoni commented on index.js
> +    existingPropertyValues.push({"name": value})
I sneaked it in here haha 😆  https://github.com/szenius/notion-update-page/pull/17/commits/593c94b3972c24c006dd5c53a845c71a31bc73af

2022-02-13 09:21 UTC, ilhaoni commented on index.js
> +      notionPropertyType: process.env.NOTION_PROPERTY_TYPE,
Have done the defaulting here: https://github.com/szenius/notion-update-page/pull/17/commits/214b92bf71fbc5950f9aab1cb9d07987b037ff7b

2022-02-13 09:22 UTC, ilhaoni commented on index.js
> +  if (!(notionPropertyType in supportedPropertyTypes)) {
Thanks for the link~~ have updated it here: https://github.com/szenius/notion-update-page/pull/17/commits/0778a07f21f4c48580f1d884845d7f5eff7b5fa0

2022-02-13 09:23 UTC, ilhaoni commented
@szenius sorry took so long to address the reviews, it's ready for review again~~

have also did a test run on my repo, it works!
![Screenshot 2022-02-13 at 5 19 14 PM](https://user-images.githubusercontent.com/5070244/153746875-9b242f3a-836e-4d46-a493-5347aede673a.png)

2022-02-14 12:36 UTC, szenius commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
Sounds good!! It was just a suggestion. If doesn't make sense, it's OK to leave as object :)

2022-02-14 12:40 UTC, ilhaoni commented on index.js
> +const supportedPropertyTypes = {"rich_text": "rich_text", "multi_select": "multi_select"};
Haha ok~~ ^^ 

It's an interesting idea though, can explore more~~

2022-02-14 12:41 UTC, szenius commented on index.js
> +      });
Ah what I meant was something like

```
const updateProps = propertyType === SUPPORTED_PROPERTY_TYPES.RICH_TEXT ? {"rich_text": ... } : {"multi_select": ...};

await notion.pages.update({
  page_id: notionPageId,
  properties: {
    [propertyName]: updateProps,
  },
});
```

So the `notion.pages.update` doesn't have to be written twice~ It's also clearer what is the difference between the two updates~

If the `...` parts are too long, can be abstracted as functions too~

2022-02-28 11:30 UTC, ilhaoni commented on index.js
> +      });
Sorry been busy 💀 

Have made the changes [here](https://github.com/szenius/notion-update-page/pull/17/commits/21c2d73baec44d4a65c000687bc0122eca93e3a9) and [here](https://github.com/szenius/notion-update-page/pull/17/commits/40ffba25b77cd2202f1a8fd128a9f805841009e7)!

Have reran o
![Screenshot 2022-02-28 at 7 28 00 PM](https://user-images.githubusercontent.com/5070244/155976241-a47e1997-7f26-425b-9ebc-64edf7e1b114.png)
n my side and it works!

2022-02-28 13:20 UTC, szenius approved these changes
lgtm!!

2022-02-28 13:20 UTC, merged